// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: cmd/proto/pb_hash.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field []byte `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HSetReq) Reset() {
	*x = HSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetReq) ProtoMessage() {}

func (x *HSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetReq.ProtoReflect.Descriptor instead.
func (*HSetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{0}
}

func (x *HSetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HSetReq) GetField() []byte {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *HSetReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type HSetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HSetRsp) Reset() {
	*x = HSetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HSetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetRsp) ProtoMessage() {}

func (x *HSetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetRsp.ProtoReflect.Descriptor instead.
func (*HSetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{1}
}

func (x *HSetRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *HSetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HSetNxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field []byte `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HSetNxReq) Reset() {
	*x = HSetNxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HSetNxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetNxReq) ProtoMessage() {}

func (x *HSetNxReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetNxReq.ProtoReflect.Descriptor instead.
func (*HSetNxReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{2}
}

func (x *HSetNxReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HSetNxReq) GetField() []byte {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *HSetNxReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type HSetNxRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HSetNxRsp) Reset() {
	*x = HSetNxRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HSetNxRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetNxRsp) ProtoMessage() {}

func (x *HSetNxRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetNxRsp.ProtoReflect.Descriptor instead.
func (*HSetNxRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{3}
}

func (x *HSetNxRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *HSetNxRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field []byte `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *HGetReq) Reset() {
	*x = HGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetReq) ProtoMessage() {}

func (x *HGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetReq.ProtoReflect.Descriptor instead.
func (*HGetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{4}
}

func (x *HGetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HGetReq) GetField() []byte {
	if x != nil {
		return x.Field
	}
	return nil
}

type HGetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HGetRsp) Reset() {
	*x = HGetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HGetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetRsp) ProtoMessage() {}

func (x *HGetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetRsp.ProtoReflect.Descriptor instead.
func (*HGetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{5}
}

func (x *HGetRsp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type HGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HGetAllReq) Reset() {
	*x = HGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetAllReq) ProtoMessage() {}

func (x *HGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetAllReq.ProtoReflect.Descriptor instead.
func (*HGetAllReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{6}
}

func (x *HGetAllReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type HGetAllRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HGetAllRsp) Reset() {
	*x = HGetAllRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HGetAllRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetAllRsp) ProtoMessage() {}

func (x *HGetAllRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetAllRsp.ProtoReflect.Descriptor instead.
func (*HGetAllRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{7}
}

func (x *HGetAllRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *HGetAllRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HMSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *HMSetReq) Reset() {
	*x = HMSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HMSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMSetReq) ProtoMessage() {}

func (x *HMSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMSetReq.ProtoReflect.Descriptor instead.
func (*HMSetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{8}
}

func (x *HMSetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HMSetReq) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type HMSetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HMSetRsp) Reset() {
	*x = HMSetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HMSetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMSetRsp) ProtoMessage() {}

func (x *HMSetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMSetRsp.ProtoReflect.Descriptor instead.
func (*HMSetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{9}
}

func (x *HMSetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HMGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields [][]byte `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *HMGetReq) Reset() {
	*x = HMGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HMGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMGetReq) ProtoMessage() {}

func (x *HMGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMGetReq.ProtoReflect.Descriptor instead.
func (*HMGetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{10}
}

func (x *HMGetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HMGetReq) GetFields() [][]byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HMGetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HMGetRsp) Reset() {
	*x = HMGetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HMGetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMGetRsp) ProtoMessage() {}

func (x *HMGetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMGetRsp.ProtoReflect.Descriptor instead.
func (*HMGetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{11}
}

func (x *HMGetRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *HMGetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HDelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields [][]byte `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *HDelReq) Reset() {
	*x = HDelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDelReq) ProtoMessage() {}

func (x *HDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDelReq.ProtoReflect.Descriptor instead.
func (*HDelReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{12}
}

func (x *HDelReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HDelReq) GetFields() [][]byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HDelRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HDelRsp) Reset() {
	*x = HDelRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HDelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDelRsp) ProtoMessage() {}

func (x *HDelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDelRsp.ProtoReflect.Descriptor instead.
func (*HDelRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{13}
}

func (x *HDelRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *HDelRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HKeyExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HKeyExistsReq) Reset() {
	*x = HKeyExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HKeyExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HKeyExistsReq) ProtoMessage() {}

func (x *HKeyExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HKeyExistsReq.ProtoReflect.Descriptor instead.
func (*HKeyExistsReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{14}
}

func (x *HKeyExistsReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type HKeyExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HKeyExistsRsp) Reset() {
	*x = HKeyExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HKeyExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HKeyExistsRsp) ProtoMessage() {}

func (x *HKeyExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HKeyExistsRsp.ProtoReflect.Descriptor instead.
func (*HKeyExistsRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{15}
}

func (x *HKeyExistsRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HKeyExistsRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field []byte `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *HExistsReq) Reset() {
	*x = HExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HExistsReq) ProtoMessage() {}

func (x *HExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HExistsReq.ProtoReflect.Descriptor instead.
func (*HExistsReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{16}
}

func (x *HExistsReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HExistsReq) GetField() []byte {
	if x != nil {
		return x.Field
	}
	return nil
}

type HExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HExistsRsp) Reset() {
	*x = HExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HExistsRsp) ProtoMessage() {}

func (x *HExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HExistsRsp.ProtoReflect.Descriptor instead.
func (*HExistsRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{17}
}

func (x *HExistsRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HExistsRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HLenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HLenReq) Reset() {
	*x = HLenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HLenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLenReq) ProtoMessage() {}

func (x *HLenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLenReq.ProtoReflect.Descriptor instead.
func (*HLenReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{18}
}

func (x *HLenReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type HLenRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length   int64  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HLenRsp) Reset() {
	*x = HLenRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HLenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLenRsp) ProtoMessage() {}

func (x *HLenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLenRsp.ProtoReflect.Descriptor instead.
func (*HLenRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{19}
}

func (x *HLenRsp) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *HLenRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HKeysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HKeysReq) Reset() {
	*x = HKeysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HKeysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HKeysReq) ProtoMessage() {}

func (x *HKeysReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HKeysReq.ProtoReflect.Descriptor instead.
func (*HKeysReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{20}
}

func (x *HKeysReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type HKeysRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HKeysRsp) Reset() {
	*x = HKeysRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HKeysRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HKeysRsp) ProtoMessage() {}

func (x *HKeysRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HKeysRsp.ProtoReflect.Descriptor instead.
func (*HKeysRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{21}
}

func (x *HKeysRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *HKeysRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HValsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HValsReq) Reset() {
	*x = HValsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HValsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HValsReq) ProtoMessage() {}

func (x *HValsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HValsReq.ProtoReflect.Descriptor instead.
func (*HValsReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{22}
}

func (x *HValsReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type HValsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HValsRsp) Reset() {
	*x = HValsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HValsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HValsRsp) ProtoMessage() {}

func (x *HValsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HValsRsp.ProtoReflect.Descriptor instead.
func (*HValsRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{23}
}

func (x *HValsRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *HValsRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HClearReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HClearReq) Reset() {
	*x = HClearReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HClearReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HClearReq) ProtoMessage() {}

func (x *HClearReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HClearReq.ProtoReflect.Descriptor instead.
func (*HClearReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{24}
}

func (x *HClearReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type HClearRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HClearRsp) Reset() {
	*x = HClearRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HClearRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HClearRsp) ProtoMessage() {}

func (x *HClearRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HClearRsp.ProtoReflect.Descriptor instead.
func (*HClearRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{25}
}

func (x *HClearRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HExpireReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Duration int64  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *HExpireReq) Reset() {
	*x = HExpireReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HExpireReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HExpireReq) ProtoMessage() {}

func (x *HExpireReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HExpireReq.ProtoReflect.Descriptor instead.
func (*HExpireReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{26}
}

func (x *HExpireReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HExpireReq) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type HExpireRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *HExpireRsp) Reset() {
	*x = HExpireRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HExpireRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HExpireRsp) ProtoMessage() {}

func (x *HExpireRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HExpireRsp.ProtoReflect.Descriptor instead.
func (*HExpireRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{27}
}

func (x *HExpireRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HTTLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HTTLReq) Reset() {
	*x = HTTLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTLReq) ProtoMessage() {}

func (x *HTTLReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTLReq.ProtoReflect.Descriptor instead.
func (*HTTLReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{28}
}

func (x *HTTLReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type HTTLRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl int64 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *HTTLRsp) Reset() {
	*x = HTTLRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_hash_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTLRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTLRsp) ProtoMessage() {}

func (x *HTTLRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_hash_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTLRsp.ProtoReflect.Descriptor instead.
func (*HTTLRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_hash_proto_rawDescGZIP(), []int{29}
}

func (x *HTTLRsp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_cmd_proto_pb_hash_proto protoreflect.FileDescriptor

var file_cmd_proto_pb_hash_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x47, 0x0a, 0x07, 0x48, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x48, 0x53, 0x65,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x49, 0x0a, 0x09, 0x48, 0x53, 0x65, 0x74, 0x4e, 0x78, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a,
	0x09, 0x48, 0x53, 0x65, 0x74, 0x4e, 0x78, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x07, 0x48, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x1f, 0x0a, 0x07, 0x48,
	0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x0a,
	0x48, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x40, 0x0a, 0x0a,
	0x48, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x34,
	0x0a, 0x08, 0x48, 0x4d, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x08, 0x48, 0x4d, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x34, 0x0a, 0x08,
	0x48, 0x4d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x22, 0x3e, 0x0a, 0x08, 0x48, 0x4d, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x33, 0x0a, 0x07, 0x48, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x37, 0x0a, 0x07, 0x48, 0x44, 0x65, 0x6c, 0x52,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x21, 0x0a, 0x0d, 0x48, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x3b, 0x0a, 0x0d, 0x48, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x34, 0x0a, 0x0a, 0x48, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x38, 0x0a, 0x0a, 0x48, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x1b, 0x0a, 0x07, 0x48, 0x4c, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3d, 0x0a,
	0x07, 0x48, 0x4c, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1c, 0x0a, 0x08,
	0x48, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3e, 0x0a, 0x08, 0x48, 0x4b,
	0x65, 0x79, 0x73, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1c, 0x0a, 0x08, 0x48, 0x56,
	0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3e, 0x0a, 0x08, 0x48, 0x56, 0x61, 0x6c,
	0x73, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1d, 0x0a, 0x09, 0x48, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x09, 0x48, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x3a, 0x0a, 0x0a, 0x48, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x0a,
	0x48, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1b, 0x0a, 0x07, 0x48, 0x54, 0x54, 0x4c, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x1b, 0x0a, 0x07, 0x48, 0x54, 0x54, 0x4c, 0x52, 0x73, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c,
	0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_pb_hash_proto_rawDescOnce sync.Once
	file_cmd_proto_pb_hash_proto_rawDescData = file_cmd_proto_pb_hash_proto_rawDesc
)

func file_cmd_proto_pb_hash_proto_rawDescGZIP() []byte {
	file_cmd_proto_pb_hash_proto_rawDescOnce.Do(func() {
		file_cmd_proto_pb_hash_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_pb_hash_proto_rawDescData)
	})
	return file_cmd_proto_pb_hash_proto_rawDescData
}

var file_cmd_proto_pb_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_cmd_proto_pb_hash_proto_goTypes = []interface{}{
	(*HSetReq)(nil),       // 0: proto.HSetReq
	(*HSetRsp)(nil),       // 1: proto.HSetRsp
	(*HSetNxReq)(nil),     // 2: proto.HSetNxReq
	(*HSetNxRsp)(nil),     // 3: proto.HSetNxRsp
	(*HGetReq)(nil),       // 4: proto.HGetReq
	(*HGetRsp)(nil),       // 5: proto.HGetRsp
	(*HGetAllReq)(nil),    // 6: proto.HGetAllReq
	(*HGetAllRsp)(nil),    // 7: proto.HGetAllRsp
	(*HMSetReq)(nil),      // 8: proto.HMSetReq
	(*HMSetRsp)(nil),      // 9: proto.HMSetRsp
	(*HMGetReq)(nil),      // 10: proto.HMGetReq
	(*HMGetRsp)(nil),      // 11: proto.HMGetRsp
	(*HDelReq)(nil),       // 12: proto.HDelReq
	(*HDelRsp)(nil),       // 13: proto.HDelRsp
	(*HKeyExistsReq)(nil), // 14: proto.HKeyExistsReq
	(*HKeyExistsRsp)(nil), // 15: proto.HKeyExistsRsp
	(*HExistsReq)(nil),    // 16: proto.HExistsReq
	(*HExistsRsp)(nil),    // 17: proto.HExistsRsp
	(*HLenReq)(nil),       // 18: proto.HLenReq
	(*HLenRsp)(nil),       // 19: proto.HLenRsp
	(*HKeysReq)(nil),      // 20: proto.HKeysReq
	(*HKeysRsp)(nil),      // 21: proto.HKeysRsp
	(*HValsReq)(nil),      // 22: proto.HValsReq
	(*HValsRsp)(nil),      // 23: proto.HValsRsp
	(*HClearReq)(nil),     // 24: proto.HClearReq
	(*HClearRsp)(nil),     // 25: proto.HClearRsp
	(*HExpireReq)(nil),    // 26: proto.HExpireReq
	(*HExpireRsp)(nil),    // 27: proto.HExpireRsp
	(*HTTLReq)(nil),       // 28: proto.HTTLReq
	(*HTTLRsp)(nil),       // 29: proto.HTTLRsp
}
var file_cmd_proto_pb_hash_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_pb_hash_proto_init() }
func file_cmd_proto_pb_hash_proto_init() {
	if File_cmd_proto_pb_hash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_pb_hash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HSetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HSetNxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HSetNxRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HGetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HGetAllRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HMSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HMSetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HMGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HMGetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HDelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HDelRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HKeyExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HKeyExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HLenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HLenRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HKeysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HKeysRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HValsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HValsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HClearReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HClearRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HExpireReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HExpireRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_hash_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTLRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_pb_hash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_pb_hash_proto_goTypes,
		DependencyIndexes: file_cmd_proto_pb_hash_proto_depIdxs,
		MessageInfos:      file_cmd_proto_pb_hash_proto_msgTypes,
	}.Build()
	File_cmd_proto_pb_hash_proto = out.File
	file_cmd_proto_pb_hash_proto_rawDesc = nil
	file_cmd_proto_pb_hash_proto_goTypes = nil
	file_cmd_proto_pb_hash_proto_depIdxs = nil
}
