// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: cmd/proto/pb_list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertOption int32

const (
	InsertOption_Before InsertOption = 0
	InsertOption_After  InsertOption = 1
)

// Enum value maps for InsertOption.
var (
	InsertOption_name = map[int32]string{
		0: "Before",
		1: "After",
	}
	InsertOption_value = map[string]int32{
		"Before": 0,
		"After":  1,
	}
)

func (x InsertOption) Enum() *InsertOption {
	p := new(InsertOption)
	*p = x
	return p
}

func (x InsertOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InsertOption) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_proto_pb_list_proto_enumTypes[0].Descriptor()
}

func (InsertOption) Type() protoreflect.EnumType {
	return &file_cmd_proto_pb_list_proto_enumTypes[0]
}

func (x InsertOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InsertOption.Descriptor instead.
func (InsertOption) EnumDescriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{0}
}

type LPushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LPushReq) Reset() {
	*x = LPushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushReq) ProtoMessage() {}

func (x *LPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushReq.ProtoReflect.Descriptor instead.
func (*LPushReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{0}
}

func (x *LPushReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LPushReq) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type LPushRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LPushRsp) Reset() {
	*x = LPushRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPushRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushRsp) ProtoMessage() {}

func (x *LPushRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushRsp.ProtoReflect.Descriptor instead.
func (*LPushRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{1}
}

func (x *LPushRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *LPushRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RPushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *RPushReq) Reset() {
	*x = RPushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushReq) ProtoMessage() {}

func (x *RPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushReq.ProtoReflect.Descriptor instead.
func (*RPushReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{2}
}

func (x *RPushReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RPushReq) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type RPushRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *RPushRsp) Reset() {
	*x = RPushRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPushRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushRsp) ProtoMessage() {}

func (x *RPushRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushRsp.ProtoReflect.Descriptor instead.
func (*RPushRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{3}
}

func (x *RPushRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *RPushRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LPopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LPopReq) Reset() {
	*x = LPopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopReq) ProtoMessage() {}

func (x *LPopReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopReq.ProtoReflect.Descriptor instead.
func (*LPopReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{4}
}

func (x *LPopReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LPopRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LPopRsp) Reset() {
	*x = LPopRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPopRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopRsp) ProtoMessage() {}

func (x *LPopRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopRsp.ProtoReflect.Descriptor instead.
func (*LPopRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{5}
}

func (x *LPopRsp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LPopRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RPopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RPopReq) Reset() {
	*x = RPopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopReq) ProtoMessage() {}

func (x *RPopReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopReq.ProtoReflect.Descriptor instead.
func (*RPopReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{6}
}

func (x *RPopReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RPopRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *RPopRsp) Reset() {
	*x = RPopRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPopRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopRsp) ProtoMessage() {}

func (x *RPopRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopRsp.ProtoReflect.Descriptor instead.
func (*RPopRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{7}
}

func (x *RPopRsp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RPopRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Idx int64  `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
}

func (x *LIndexReq) Reset() {
	*x = LIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LIndexReq) ProtoMessage() {}

func (x *LIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LIndexReq.ProtoReflect.Descriptor instead.
func (*LIndexReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{8}
}

func (x *LIndexReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LIndexReq) GetIdx() int64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type LIndexRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LIndexRsp) Reset() {
	*x = LIndexRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LIndexRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LIndexRsp) ProtoMessage() {}

func (x *LIndexRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LIndexRsp.ProtoReflect.Descriptor instead.
func (*LIndexRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{9}
}

func (x *LIndexRsp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LIndexRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LRemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Count int64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *LRemReq) Reset() {
	*x = LRemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRemReq) ProtoMessage() {}

func (x *LRemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRemReq.ProtoReflect.Descriptor instead.
func (*LRemReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{10}
}

func (x *LRemReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LRemReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LRemReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LRemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LRemRsp) Reset() {
	*x = LRemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRemRsp) ProtoMessage() {}

func (x *LRemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRemRsp.ProtoReflect.Descriptor instead.
func (*LRemRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{11}
}

func (x *LRemRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *LRemRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LInsertReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Option InsertOption `protobuf:"varint,2,opt,name=option,proto3,enum=proto.InsertOption" json:"option,omitempty"`
	Pivot  []byte       `protobuf:"bytes,3,opt,name=pivot,proto3" json:"pivot,omitempty"`
	Value  []byte       `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LInsertReq) Reset() {
	*x = LInsertReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LInsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LInsertReq) ProtoMessage() {}

func (x *LInsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LInsertReq.ProtoReflect.Descriptor instead.
func (*LInsertReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{12}
}

func (x *LInsertReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LInsertReq) GetOption() InsertOption {
	if x != nil {
		return x.Option
	}
	return InsertOption_Before
}

func (x *LInsertReq) GetPivot() []byte {
	if x != nil {
		return x.Pivot
	}
	return nil
}

func (x *LInsertReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LInsertRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    int64  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LInsertRsp) Reset() {
	*x = LInsertRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LInsertRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LInsertRsp) ProtoMessage() {}

func (x *LInsertRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LInsertRsp.ProtoReflect.Descriptor instead.
func (*LInsertRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{13}
}

func (x *LInsertRsp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LInsertRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Idx   int64  `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LSetReq) Reset() {
	*x = LSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSetReq) ProtoMessage() {}

func (x *LSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSetReq.ProtoReflect.Descriptor instead.
func (*LSetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{14}
}

func (x *LSetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LSetReq) GetIdx() int64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LSetReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LSetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LSetRsp) Reset() {
	*x = LSetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LSetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSetRsp) ProtoMessage() {}

func (x *LSetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSetRsp.ProtoReflect.Descriptor instead.
func (*LSetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{15}
}

func (x *LSetRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LSetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LTrimReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int64  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *LTrimReq) Reset() {
	*x = LTrimReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LTrimReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTrimReq) ProtoMessage() {}

func (x *LTrimReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTrimReq.ProtoReflect.Descriptor instead.
func (*LTrimReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{16}
}

func (x *LTrimReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LTrimReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LTrimReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type LTrimRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LTrimRsp) Reset() {
	*x = LTrimRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LTrimRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTrimRsp) ProtoMessage() {}

func (x *LTrimRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTrimRsp.ProtoReflect.Descriptor instead.
func (*LTrimRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{17}
}

func (x *LTrimRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LRangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int64  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *LRangeReq) Reset() {
	*x = LRangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeReq) ProtoMessage() {}

func (x *LRangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeReq.ProtoReflect.Descriptor instead.
func (*LRangeReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{18}
}

func (x *LRangeReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LRangeReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LRangeReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type LRangeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LRangeRsp) Reset() {
	*x = LRangeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRangeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeRsp) ProtoMessage() {}

func (x *LRangeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeRsp.ProtoReflect.Descriptor instead.
func (*LRangeRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{19}
}

func (x *LRangeRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *LRangeRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LLenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LLenReq) Reset() {
	*x = LLenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLenReq) ProtoMessage() {}

func (x *LLenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLenReq.ProtoReflect.Descriptor instead.
func (*LLenReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{20}
}

func (x *LLenReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LLenRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int64 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *LLenRsp) Reset() {
	*x = LLenRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLenRsp) ProtoMessage() {}

func (x *LLenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLenRsp.ProtoReflect.Descriptor instead.
func (*LLenRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{21}
}

func (x *LLenRsp) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type LKeyExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LKeyExistsReq) Reset() {
	*x = LKeyExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LKeyExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LKeyExistsReq) ProtoMessage() {}

func (x *LKeyExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LKeyExistsReq.ProtoReflect.Descriptor instead.
func (*LKeyExistsReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{22}
}

func (x *LKeyExistsReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LKeyExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LKeyExistsRsp) Reset() {
	*x = LKeyExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LKeyExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LKeyExistsRsp) ProtoMessage() {}

func (x *LKeyExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LKeyExistsRsp.ProtoReflect.Descriptor instead.
func (*LKeyExistsRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{23}
}

func (x *LKeyExistsRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LKeyExistsRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LValExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LValExistsReq) Reset() {
	*x = LValExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LValExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LValExistsReq) ProtoMessage() {}

func (x *LValExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LValExistsReq.ProtoReflect.Descriptor instead.
func (*LValExistsReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{24}
}

func (x *LValExistsReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LValExistsReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LValExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LValExistsRsp) Reset() {
	*x = LValExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LValExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LValExistsRsp) ProtoMessage() {}

func (x *LValExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LValExistsRsp.ProtoReflect.Descriptor instead.
func (*LValExistsRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{25}
}

func (x *LValExistsRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LValExistsRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LClearReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LClearReq) Reset() {
	*x = LClearReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LClearReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LClearReq) ProtoMessage() {}

func (x *LClearReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LClearReq.ProtoReflect.Descriptor instead.
func (*LClearReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{26}
}

func (x *LClearReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LClearRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LClearRsp) Reset() {
	*x = LClearRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LClearRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LClearRsp) ProtoMessage() {}

func (x *LClearRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LClearRsp.ProtoReflect.Descriptor instead.
func (*LClearRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{27}
}

func (x *LClearRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LExpireReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Duration int64  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *LExpireReq) Reset() {
	*x = LExpireReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LExpireReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LExpireReq) ProtoMessage() {}

func (x *LExpireReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LExpireReq.ProtoReflect.Descriptor instead.
func (*LExpireReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{28}
}

func (x *LExpireReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LExpireReq) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type LExpireRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LExpireRsp) Reset() {
	*x = LExpireRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LExpireRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LExpireRsp) ProtoMessage() {}

func (x *LExpireRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LExpireRsp.ProtoReflect.Descriptor instead.
func (*LExpireRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{29}
}

func (x *LExpireRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LTTLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LTTLReq) Reset() {
	*x = LTTLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LTTLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTTLReq) ProtoMessage() {}

func (x *LTTLReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTTLReq.ProtoReflect.Descriptor instead.
func (*LTTLReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{30}
}

func (x *LTTLReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LTTLRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl int64 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *LTTLRsp) Reset() {
	*x = LTTLRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_list_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LTTLRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTTLRsp) ProtoMessage() {}

func (x *LTTLRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_list_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTTLRsp.ProtoReflect.Descriptor instead.
func (*LTTLRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_list_proto_rawDescGZIP(), []int{31}
}

func (x *LTTLRsp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_cmd_proto_pb_list_proto protoreflect.FileDescriptor

var file_cmd_proto_pb_list_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x34, 0x0a, 0x08, 0x4c, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x4c, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x34, 0x0a, 0x08, 0x52, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x1b, 0x0a, 0x07, 0x4c, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3b, 0x0a,
	0x07, 0x4c, 0x50, 0x6f, 0x70, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1b, 0x0a, 0x07, 0x52, 0x50,
	0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3b, 0x0a, 0x07, 0x52, 0x50, 0x6f, 0x70, 0x52,
	0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x2f, 0x0a, 0x09, 0x4c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x69, 0x64, 0x78, 0x22, 0x3d, 0x0a, 0x09, 0x4c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52,
	0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x47, 0x0a, 0x07, 0x4c, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x37, 0x0a,
	0x07, 0x4c, 0x52, 0x65, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x77, 0x0a, 0x0a, 0x4c, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x76, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x70, 0x69, 0x76, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x3e, 0x0a, 0x0a, 0x4c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22,
	0x43, 0x0a, 0x07, 0x4c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x07, 0x4c, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x44, 0x0a, 0x08, 0x4c,
	0x54, 0x72, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e,
	0x64, 0x22, 0x26, 0x0a, 0x08, 0x4c, 0x54, 0x72, 0x69, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x09, 0x4c, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64,
	0x22, 0x3f, 0x0a, 0x09, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0x1b, 0x0a, 0x07, 0x4c, 0x4c, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x21,
	0x0a, 0x07, 0x4c, 0x4c, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x22, 0x21, 0x0a, 0x0d, 0x4c, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x3b, 0x0a, 0x0d, 0x4c, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0x37, 0x0a, 0x0d, 0x4c, 0x56, 0x61, 0x6c, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x0d, 0x4c, 0x56,
	0x61, 0x6c, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1d, 0x0a, 0x09, 0x4c, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x09, 0x4c, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22,
	0x3a, 0x0a, 0x0a, 0x4c, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x0a, 0x4c,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1b, 0x0a, 0x07, 0x4c, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x1b, 0x0a, 0x07, 0x4c, 0x54, 0x54, 0x4c, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x74, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x2a,
	0x25, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0a, 0x0a, 0x06, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x66, 0x74, 0x65, 0x72, 0x10, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_pb_list_proto_rawDescOnce sync.Once
	file_cmd_proto_pb_list_proto_rawDescData = file_cmd_proto_pb_list_proto_rawDesc
)

func file_cmd_proto_pb_list_proto_rawDescGZIP() []byte {
	file_cmd_proto_pb_list_proto_rawDescOnce.Do(func() {
		file_cmd_proto_pb_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_pb_list_proto_rawDescData)
	})
	return file_cmd_proto_pb_list_proto_rawDescData
}

var file_cmd_proto_pb_list_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_proto_pb_list_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_cmd_proto_pb_list_proto_goTypes = []interface{}{
	(InsertOption)(0),     // 0: proto.InsertOption
	(*LPushReq)(nil),      // 1: proto.LPushReq
	(*LPushRsp)(nil),      // 2: proto.LPushRsp
	(*RPushReq)(nil),      // 3: proto.RPushReq
	(*RPushRsp)(nil),      // 4: proto.RPushRsp
	(*LPopReq)(nil),       // 5: proto.LPopReq
	(*LPopRsp)(nil),       // 6: proto.LPopRsp
	(*RPopReq)(nil),       // 7: proto.RPopReq
	(*RPopRsp)(nil),       // 8: proto.RPopRsp
	(*LIndexReq)(nil),     // 9: proto.LIndexReq
	(*LIndexRsp)(nil),     // 10: proto.LIndexRsp
	(*LRemReq)(nil),       // 11: proto.LRemReq
	(*LRemRsp)(nil),       // 12: proto.LRemRsp
	(*LInsertReq)(nil),    // 13: proto.LInsertReq
	(*LInsertRsp)(nil),    // 14: proto.LInsertRsp
	(*LSetReq)(nil),       // 15: proto.LSetReq
	(*LSetRsp)(nil),       // 16: proto.LSetRsp
	(*LTrimReq)(nil),      // 17: proto.LTrimReq
	(*LTrimRsp)(nil),      // 18: proto.LTrimRsp
	(*LRangeReq)(nil),     // 19: proto.LRangeReq
	(*LRangeRsp)(nil),     // 20: proto.LRangeRsp
	(*LLenReq)(nil),       // 21: proto.LLenReq
	(*LLenRsp)(nil),       // 22: proto.LLenRsp
	(*LKeyExistsReq)(nil), // 23: proto.LKeyExistsReq
	(*LKeyExistsRsp)(nil), // 24: proto.LKeyExistsRsp
	(*LValExistsReq)(nil), // 25: proto.LValExistsReq
	(*LValExistsRsp)(nil), // 26: proto.LValExistsRsp
	(*LClearReq)(nil),     // 27: proto.LClearReq
	(*LClearRsp)(nil),     // 28: proto.LClearRsp
	(*LExpireReq)(nil),    // 29: proto.LExpireReq
	(*LExpireRsp)(nil),    // 30: proto.LExpireRsp
	(*LTTLReq)(nil),       // 31: proto.LTTLReq
	(*LTTLRsp)(nil),       // 32: proto.LTTLRsp
}
var file_cmd_proto_pb_list_proto_depIdxs = []int32{
	0, // 0: proto.LInsertReq.option:type_name -> proto.InsertOption
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_proto_pb_list_proto_init() }
func file_cmd_proto_pb_list_proto_init() {
	if File_cmd_proto_pb_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_pb_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPushRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPushRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPopRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPopRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LIndexRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LInsertReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LInsertRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LSetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LTrimReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LTrimRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRangeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLenRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LKeyExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LKeyExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LValExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LValExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LClearReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LClearRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LExpireReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LExpireRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LTTLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_list_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LTTLRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_pb_list_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_pb_list_proto_goTypes,
		DependencyIndexes: file_cmd_proto_pb_list_proto_depIdxs,
		EnumInfos:         file_cmd_proto_pb_list_proto_enumTypes,
		MessageInfos:      file_cmd_proto_pb_list_proto_msgTypes,
	}.Build()
	File_cmd_proto_pb_list_proto = out.File
	file_cmd_proto_pb_list_proto_rawDesc = nil
	file_cmd_proto_pb_list_proto_goTypes = nil
	file_cmd_proto_pb_list_proto_depIdxs = nil
}
