// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: cmd/proto/pb_str.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []byte `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{0}
}

func (x *SetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetReq) GetValues() []byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type SetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SetRsp) Reset() {
	*x = SetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRsp) ProtoMessage() {}

func (x *SetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRsp.ProtoReflect.Descriptor instead.
func (*SetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{1}
}

func (x *SetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SetNxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetNxReq) Reset() {
	*x = SetNxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNxReq) ProtoMessage() {}

func (x *SetNxReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNxReq.ProtoReflect.Descriptor instead.
func (*SetNxReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{2}
}

func (x *SetNxReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetNxReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetNxRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SetNxRsp) Reset() {
	*x = SetNxRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNxRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNxRsp) ProtoMessage() {}

func (x *SetNxRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNxRsp.ProtoReflect.Descriptor instead.
func (*SetNxRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{3}
}

func (x *SetNxRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetNxRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SetExReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Duration int64  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *SetExReq) Reset() {
	*x = SetExReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetExReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExReq) ProtoMessage() {}

func (x *SetExReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExReq.ProtoReflect.Descriptor instead.
func (*SetExReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{4}
}

func (x *SetExReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetExReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetExReq) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type SetExRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SetExRsp) Reset() {
	*x = SetExRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetExRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExRsp) ProtoMessage() {}

func (x *SetExRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExRsp.ProtoReflect.Descriptor instead.
func (*SetExRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{5}
}

func (x *SetExRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{6}
}

func (x *GetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest     []byte `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *GetRsp) Reset() {
	*x = GetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRsp) ProtoMessage() {}

func (x *GetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRsp.ProtoReflect.Descriptor instead.
func (*GetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{7}
}

func (x *GetRsp) GetDest() []byte {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *GetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetSetReq) Reset() {
	*x = GetSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetReq) ProtoMessage() {}

func (x *GetSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetReq.ProtoReflect.Descriptor instead.
func (*GetSetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{8}
}

func (x *GetSetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetSetReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetSetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest     []byte `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *GetSetRsp) Reset() {
	*x = GetSetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetRsp) ProtoMessage() {}

func (x *GetSetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetRsp.ProtoReflect.Descriptor instead.
func (*GetSetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{9}
}

func (x *GetSetRsp) GetDest() []byte {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *GetSetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type MSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys   [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *MSetReq) Reset() {
	*x = MSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSetReq) ProtoMessage() {}

func (x *MSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSetReq.ProtoReflect.Descriptor instead.
func (*MSetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{10}
}

func (x *MSetReq) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MSetReq) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type MSetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *MSetRsp) Reset() {
	*x = MSetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSetRsp) ProtoMessage() {}

func (x *MSetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSetRsp.ProtoReflect.Descriptor instead.
func (*MSetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{11}
}

func (x *MSetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type MGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *MGetReq) Reset() {
	*x = MGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetReq) ProtoMessage() {}

func (x *MGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetReq.ProtoReflect.Descriptor instead.
func (*MGetReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{12}
}

func (x *MGetReq) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type MGetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *MGetRsp) Reset() {
	*x = MGetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MGetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetRsp) ProtoMessage() {}

func (x *MGetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetRsp.ProtoReflect.Descriptor instead.
func (*MGetRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{13}
}

func (x *MGetRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *MGetRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type AppendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AppendReq) Reset() {
	*x = AppendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendReq) ProtoMessage() {}

func (x *AppendReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendReq.ProtoReflect.Descriptor instead.
func (*AppendReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{14}
}

func (x *AppendReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AppendReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type AppendRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *AppendRsp) Reset() {
	*x = AppendRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRsp) ProtoMessage() {}

func (x *AppendRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRsp.ProtoReflect.Descriptor instead.
func (*AppendRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{15}
}

func (x *AppendRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RemoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RemoveReq) Reset() {
	*x = RemoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReq) ProtoMessage() {}

func (x *RemoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReq.ProtoReflect.Descriptor instead.
func (*RemoveReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RemoveRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *RemoveRsp) Reset() {
	*x = RemoveRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRsp) ProtoMessage() {}

func (x *RemoveRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRsp.ProtoReflect.Descriptor instead.
func (*RemoveRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type PrefixScanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *PrefixScanReq) Reset() {
	*x = PrefixScanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrefixScanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixScanReq) ProtoMessage() {}

func (x *PrefixScanReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixScanReq.ProtoReflect.Descriptor instead.
func (*PrefixScanReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{18}
}

func (x *PrefixScanReq) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *PrefixScanReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PrefixScanReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PrefixScanRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *PrefixScanRsp) Reset() {
	*x = PrefixScanRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrefixScanRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixScanRsp) ProtoMessage() {}

func (x *PrefixScanRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixScanRsp.ProtoReflect.Descriptor instead.
func (*PrefixScanRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{19}
}

func (x *PrefixScanRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *PrefixScanRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RangeScanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   []byte `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *RangeScanReq) Reset() {
	*x = RangeScanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeScanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeScanReq) ProtoMessage() {}

func (x *RangeScanReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeScanReq.ProtoReflect.Descriptor instead.
func (*RangeScanReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{20}
}

func (x *RangeScanReq) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RangeScanReq) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

type RangeScanRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *RangeScanRsp) Reset() {
	*x = RangeScanRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeScanRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeScanRsp) ProtoMessage() {}

func (x *RangeScanRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeScanRsp.ProtoReflect.Descriptor instead.
func (*RangeScanRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{21}
}

func (x *RangeScanRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *RangeScanRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ExpireReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Duration int64  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *ExpireReq) Reset() {
	*x = ExpireReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpireReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireReq) ProtoMessage() {}

func (x *ExpireReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireReq.ProtoReflect.Descriptor instead.
func (*ExpireReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{22}
}

func (x *ExpireReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ExpireReq) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type ExpireRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ExpireRsp) Reset() {
	*x = ExpireRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpireRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireRsp) ProtoMessage() {}

func (x *ExpireRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireRsp.ProtoReflect.Descriptor instead.
func (*ExpireRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{23}
}

func (x *ExpireRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type PersistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *PersistReq) Reset() {
	*x = PersistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistReq) ProtoMessage() {}

func (x *PersistReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistReq.ProtoReflect.Descriptor instead.
func (*PersistReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{24}
}

func (x *PersistReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type PersistRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *PersistRsp) Reset() {
	*x = PersistRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistRsp) ProtoMessage() {}

func (x *PersistRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistRsp.ProtoReflect.Descriptor instead.
func (*PersistRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{25}
}

func (x *PersistRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type TTLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *TTLReq) Reset() {
	*x = TTLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTLReq) ProtoMessage() {}

func (x *TTLReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTLReq.ProtoReflect.Descriptor instead.
func (*TTLReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{26}
}

func (x *TTLReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type TTLRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl int64 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *TTLRsp) Reset() {
	*x = TTLRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTLRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTLRsp) ProtoMessage() {}

func (x *TTLRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTLRsp.ProtoReflect.Descriptor instead.
func (*TTLRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{27}
}

func (x *TTLRsp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type StrExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *StrExistsReq) Reset() {
	*x = StrExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrExistsReq) ProtoMessage() {}

func (x *StrExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrExistsReq.ProtoReflect.Descriptor instead.
func (*StrExistsReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{28}
}

func (x *StrExistsReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type StrExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *StrExistsRsp) Reset() {
	*x = StrExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_str_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrExistsRsp) ProtoMessage() {}

func (x *StrExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_str_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrExistsRsp.ProtoReflect.Descriptor instead.
func (*StrExistsRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_str_proto_rawDescGZIP(), []int{29}
}

func (x *StrExistsRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StrExistsRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_cmd_proto_pb_str_proto protoreflect.FileDescriptor

var file_cmd_proto_pb_str_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x73,
	0x74, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x32, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x32, 0x0a, 0x08, 0x53, 0x65, 0x74,
	0x4e, 0x78, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a,
	0x08, 0x53, 0x65, 0x74, 0x4e, 0x78, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x4e, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x45, 0x78, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x26, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x45, 0x78, 0x52, 0x73,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1a, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x38, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x33, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x35, 0x0a, 0x07, 0x4d, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x07,
	0x4d, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0x3d, 0x0a, 0x07, 0x4d, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0x33, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22,
	0x1d, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x27,
	0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x55, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x43,
	0x0a, 0x0d, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x36, 0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x42, 0x0a, 0x0c, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22,
	0x39, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x09, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x1e, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x28, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1a, 0x0a,
	0x06, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x1a, 0x0a, 0x06, 0x54, 0x54, 0x4c,
	0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0x20, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3a, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_pb_str_proto_rawDescOnce sync.Once
	file_cmd_proto_pb_str_proto_rawDescData = file_cmd_proto_pb_str_proto_rawDesc
)

func file_cmd_proto_pb_str_proto_rawDescGZIP() []byte {
	file_cmd_proto_pb_str_proto_rawDescOnce.Do(func() {
		file_cmd_proto_pb_str_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_pb_str_proto_rawDescData)
	})
	return file_cmd_proto_pb_str_proto_rawDescData
}

var file_cmd_proto_pb_str_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_cmd_proto_pb_str_proto_goTypes = []interface{}{
	(*SetReq)(nil),        // 0: proto.SetReq
	(*SetRsp)(nil),        // 1: proto.SetRsp
	(*SetNxReq)(nil),      // 2: proto.SetNxReq
	(*SetNxRsp)(nil),      // 3: proto.SetNxRsp
	(*SetExReq)(nil),      // 4: proto.SetExReq
	(*SetExRsp)(nil),      // 5: proto.SetExRsp
	(*GetReq)(nil),        // 6: proto.GetReq
	(*GetRsp)(nil),        // 7: proto.GetRsp
	(*GetSetReq)(nil),     // 8: proto.GetSetReq
	(*GetSetRsp)(nil),     // 9: proto.GetSetRsp
	(*MSetReq)(nil),       // 10: proto.MSetReq
	(*MSetRsp)(nil),       // 11: proto.MSetRsp
	(*MGetReq)(nil),       // 12: proto.MGetReq
	(*MGetRsp)(nil),       // 13: proto.MGetRsp
	(*AppendReq)(nil),     // 14: proto.AppendReq
	(*AppendRsp)(nil),     // 15: proto.AppendRsp
	(*RemoveReq)(nil),     // 16: proto.RemoveReq
	(*RemoveRsp)(nil),     // 17: proto.RemoveRsp
	(*PrefixScanReq)(nil), // 18: proto.PrefixScanReq
	(*PrefixScanRsp)(nil), // 19: proto.PrefixScanRsp
	(*RangeScanReq)(nil),  // 20: proto.RangeScanReq
	(*RangeScanRsp)(nil),  // 21: proto.RangeScanRsp
	(*ExpireReq)(nil),     // 22: proto.ExpireReq
	(*ExpireRsp)(nil),     // 23: proto.ExpireRsp
	(*PersistReq)(nil),    // 24: proto.PersistReq
	(*PersistRsp)(nil),    // 25: proto.PersistRsp
	(*TTLReq)(nil),        // 26: proto.TTLReq
	(*TTLRsp)(nil),        // 27: proto.TTLRsp
	(*StrExistsReq)(nil),  // 28: proto.StrExistsReq
	(*StrExistsRsp)(nil),  // 29: proto.StrExistsRsp
}
var file_cmd_proto_pb_str_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_pb_str_proto_init() }
func file_cmd_proto_pb_str_proto_init() {
	if File_cmd_proto_pb_str_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_pb_str_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNxRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetExReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetExRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MGetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrefixScanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrefixScanRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeScanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeScanRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpireReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpireRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTLRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_str_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_pb_str_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_pb_str_proto_goTypes,
		DependencyIndexes: file_cmd_proto_pb_str_proto_depIdxs,
		MessageInfos:      file_cmd_proto_pb_str_proto_msgTypes,
	}.Build()
	File_cmd_proto_pb_str_proto = out.File
	file_cmd_proto_pb_str_proto_rawDesc = nil
	file_cmd_proto_pb_str_proto_goTypes = nil
	file_cmd_proto_pb_str_proto_depIdxs = nil
}
