// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: cmd/proto/pb_set.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members [][]byte `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SAddReq) Reset() {
	*x = SAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddReq) ProtoMessage() {}

func (x *SAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddReq.ProtoReflect.Descriptor instead.
func (*SAddReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{0}
}

func (x *SAddReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SAddReq) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

type SAddRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SAddRsp) Reset() {
	*x = SAddRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAddRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddRsp) ProtoMessage() {}

func (x *SAddRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddRsp.ProtoReflect.Descriptor instead.
func (*SAddRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{1}
}

func (x *SAddRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *SAddRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SPopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SPopReq) Reset() {
	*x = SPopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPopReq) ProtoMessage() {}

func (x *SPopReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPopReq.ProtoReflect.Descriptor instead.
func (*SPopReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{2}
}

func (x *SPopReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SPopReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SPopRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SPopRsp) Reset() {
	*x = SPopRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPopRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPopRsp) ProtoMessage() {}

func (x *SPopRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPopRsp.ProtoReflect.Descriptor instead.
func (*SPopRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{3}
}

func (x *SPopRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SPopRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SIsMemberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member []byte `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *SIsMemberReq) Reset() {
	*x = SIsMemberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SIsMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberReq) ProtoMessage() {}

func (x *SIsMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberReq.ProtoReflect.Descriptor instead.
func (*SIsMemberReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{4}
}

func (x *SIsMemberReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SIsMemberReq) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

type SIsMemberRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMember bool   `protobuf:"varint,1,opt,name=isMember,proto3" json:"isMember,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SIsMemberRsp) Reset() {
	*x = SIsMemberRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SIsMemberRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberRsp) ProtoMessage() {}

func (x *SIsMemberRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberRsp.ProtoReflect.Descriptor instead.
func (*SIsMemberRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{5}
}

func (x *SIsMemberRsp) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *SIsMemberRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SRandMemberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SRandMemberReq) Reset() {
	*x = SRandMemberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRandMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRandMemberReq) ProtoMessage() {}

func (x *SRandMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRandMemberReq.ProtoReflect.Descriptor instead.
func (*SRandMemberReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{6}
}

func (x *SRandMemberReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SRandMemberReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SRandMemberRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SRandMemberRsp) Reset() {
	*x = SRandMemberRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRandMemberRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRandMemberRsp) ProtoMessage() {}

func (x *SRandMemberRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRandMemberRsp.ProtoReflect.Descriptor instead.
func (*SRandMemberRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{7}
}

func (x *SRandMemberRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SRandMemberRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SRemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members [][]byte `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SRemReq) Reset() {
	*x = SRemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemReq) ProtoMessage() {}

func (x *SRemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemReq.ProtoReflect.Descriptor instead.
func (*SRemReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{8}
}

func (x *SRemReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SRemReq) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

type SRemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SRemRsp) Reset() {
	*x = SRemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemRsp) ProtoMessage() {}

func (x *SRemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemRsp.ProtoReflect.Descriptor instead.
func (*SRemRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{9}
}

func (x *SRemRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *SRemRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src    []byte `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst    []byte `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Member []byte `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *SMoveReq) Reset() {
	*x = SMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMoveReq) ProtoMessage() {}

func (x *SMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMoveReq.ProtoReflect.Descriptor instead.
func (*SMoveReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{10}
}

func (x *SMoveReq) GetSrc() []byte {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *SMoveReq) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *SMoveReq) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

type SMoveRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SMoveRsp) Reset() {
	*x = SMoveRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMoveRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMoveRsp) ProtoMessage() {}

func (x *SMoveRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMoveRsp.ProtoReflect.Descriptor instead.
func (*SMoveRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{11}
}

func (x *SMoveRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SCardReq) Reset() {
	*x = SCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardReq) ProtoMessage() {}

func (x *SCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardReq.ProtoReflect.Descriptor instead.
func (*SCardReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{12}
}

func (x *SCardReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SCardRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res      int64  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SCardRsp) Reset() {
	*x = SCardRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardRsp) ProtoMessage() {}

func (x *SCardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardRsp.ProtoReflect.Descriptor instead.
func (*SCardRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{13}
}

func (x *SCardRsp) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *SCardRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SMembersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SMembersReq) Reset() {
	*x = SMembersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersReq) ProtoMessage() {}

func (x *SMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersReq.ProtoReflect.Descriptor instead.
func (*SMembersReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{14}
}

func (x *SMembersReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SMembersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SMembersRsp) Reset() {
	*x = SMembersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersRsp) ProtoMessage() {}

func (x *SMembersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersRsp.ProtoReflect.Descriptor instead.
func (*SMembersRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{15}
}

func (x *SMembersRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SMembersRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SUnionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys     [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SUnionReq) Reset() {
	*x = SUnionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SUnionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SUnionReq) ProtoMessage() {}

func (x *SUnionReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SUnionReq.ProtoReflect.Descriptor instead.
func (*SUnionReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{16}
}

func (x *SUnionReq) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SUnionReq) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SUnionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SUnionRsp) Reset() {
	*x = SUnionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SUnionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SUnionRsp) ProtoMessage() {}

func (x *SUnionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SUnionRsp.ProtoReflect.Descriptor instead.
func (*SUnionRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{17}
}

func (x *SUnionRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SUnionRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SDiffReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SDiffReq) Reset() {
	*x = SDiffReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDiffReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDiffReq) ProtoMessage() {}

func (x *SDiffReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDiffReq.ProtoReflect.Descriptor instead.
func (*SDiffReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{18}
}

func (x *SDiffReq) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SDiffRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SDiffRsp) Reset() {
	*x = SDiffRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDiffRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDiffRsp) ProtoMessage() {}

func (x *SDiffRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDiffRsp.ProtoReflect.Descriptor instead.
func (*SDiffRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{19}
}

func (x *SDiffRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SDiffRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SKeyExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SKeyExistsReq) Reset() {
	*x = SKeyExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKeyExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKeyExistsReq) ProtoMessage() {}

func (x *SKeyExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKeyExistsReq.ProtoReflect.Descriptor instead.
func (*SKeyExistsReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{20}
}

func (x *SKeyExistsReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SKeyExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SKeyExistsRsp) Reset() {
	*x = SKeyExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKeyExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKeyExistsRsp) ProtoMessage() {}

func (x *SKeyExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKeyExistsRsp.ProtoReflect.Descriptor instead.
func (*SKeyExistsRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{21}
}

func (x *SKeyExistsRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SKeyExistsRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SClearReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SClearReq) Reset() {
	*x = SClearReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SClearReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SClearReq) ProtoMessage() {}

func (x *SClearReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SClearReq.ProtoReflect.Descriptor instead.
func (*SClearReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{22}
}

func (x *SClearReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SClearRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SClearRsp) Reset() {
	*x = SClearRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SClearRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SClearRsp) ProtoMessage() {}

func (x *SClearRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SClearRsp.ProtoReflect.Descriptor instead.
func (*SClearRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{23}
}

func (x *SClearRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SClearRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SExpireReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Duration int64  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *SExpireReq) Reset() {
	*x = SExpireReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SExpireReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SExpireReq) ProtoMessage() {}

func (x *SExpireReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SExpireReq.ProtoReflect.Descriptor instead.
func (*SExpireReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{24}
}

func (x *SExpireReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SExpireReq) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type SExpireRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *SExpireRsp) Reset() {
	*x = SExpireRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SExpireRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SExpireRsp) ProtoMessage() {}

func (x *SExpireRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SExpireRsp.ProtoReflect.Descriptor instead.
func (*SExpireRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{25}
}

func (x *SExpireRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type STTLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *STTLReq) Reset() {
	*x = STTLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *STTLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STTLReq) ProtoMessage() {}

func (x *STTLReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STTLReq.ProtoReflect.Descriptor instead.
func (*STTLReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{26}
}

func (x *STTLReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type STTLRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl int64 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *STTLRsp) Reset() {
	*x = STTLRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_set_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *STTLRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STTLRsp) ProtoMessage() {}

func (x *STTLRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_set_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STTLRsp.ProtoReflect.Descriptor instead.
func (*STTLRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_set_proto_rawDescGZIP(), []int{27}
}

func (x *STTLRsp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_cmd_proto_pb_set_proto protoreflect.FileDescriptor

var file_cmd_proto_pb_set_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x73,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x35, 0x0a, 0x07, 0x53, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x37, 0x0a, 0x07, 0x53, 0x41, 0x64, 0x64, 0x52, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22,
	0x31, 0x0a, 0x07, 0x53, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x07, 0x53, 0x50, 0x6f, 0x70, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0x38, 0x0a, 0x0c, 0x53, 0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x46, 0x0a, 0x0c, 0x53,
	0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x38, 0x0a, 0x0e, 0x53, 0x52, 0x61, 0x6e, 0x64, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x44, 0x0a,
	0x0e, 0x53, 0x52, 0x61, 0x6e, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x35, 0x0a, 0x07, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x37, 0x0a, 0x07, 0x53, 0x52,
	0x65, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x46, 0x0a, 0x08, 0x53, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x72,
	0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x64, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x08, 0x53,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x1c, 0x0a, 0x08, 0x53, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x38, 0x0a, 0x08, 0x53, 0x43, 0x61, 0x72, 0x64, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1f, 0x0a, 0x0b, 0x53,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x41, 0x0a, 0x0b,
	0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22,
	0x3b, 0x0a, 0x09, 0x53, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x3f, 0x0a, 0x09,
	0x53, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1e, 0x0a,
	0x08, 0x53, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x3e, 0x0a,
	0x08, 0x53, 0x44, 0x69, 0x66, 0x66, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x21, 0x0a,
	0x0d, 0x53, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x3b, 0x0a, 0x0d, 0x53, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x73,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1d, 0x0a,
	0x09, 0x53, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x09,
	0x53, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x3a, 0x0a, 0x0a, 0x53, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x28, 0x0a, 0x0a, 0x53, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1b, 0x0a, 0x07, 0x53,
	0x54, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x1b, 0x0a, 0x07, 0x53, 0x54, 0x54, 0x4c,
	0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x74, 0x74, 0x6c, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_pb_set_proto_rawDescOnce sync.Once
	file_cmd_proto_pb_set_proto_rawDescData = file_cmd_proto_pb_set_proto_rawDesc
)

func file_cmd_proto_pb_set_proto_rawDescGZIP() []byte {
	file_cmd_proto_pb_set_proto_rawDescOnce.Do(func() {
		file_cmd_proto_pb_set_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_pb_set_proto_rawDescData)
	})
	return file_cmd_proto_pb_set_proto_rawDescData
}

var file_cmd_proto_pb_set_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_cmd_proto_pb_set_proto_goTypes = []interface{}{
	(*SAddReq)(nil),        // 0: proto.SAddReq
	(*SAddRsp)(nil),        // 1: proto.SAddRsp
	(*SPopReq)(nil),        // 2: proto.SPopReq
	(*SPopRsp)(nil),        // 3: proto.SPopRsp
	(*SIsMemberReq)(nil),   // 4: proto.SIsMemberReq
	(*SIsMemberRsp)(nil),   // 5: proto.SIsMemberRsp
	(*SRandMemberReq)(nil), // 6: proto.SRandMemberReq
	(*SRandMemberRsp)(nil), // 7: proto.SRandMemberRsp
	(*SRemReq)(nil),        // 8: proto.SRemReq
	(*SRemRsp)(nil),        // 9: proto.SRemRsp
	(*SMoveReq)(nil),       // 10: proto.SMoveReq
	(*SMoveRsp)(nil),       // 11: proto.SMoveRsp
	(*SCardReq)(nil),       // 12: proto.SCardReq
	(*SCardRsp)(nil),       // 13: proto.SCardRsp
	(*SMembersReq)(nil),    // 14: proto.SMembersReq
	(*SMembersRsp)(nil),    // 15: proto.SMembersRsp
	(*SUnionReq)(nil),      // 16: proto.SUnionReq
	(*SUnionRsp)(nil),      // 17: proto.SUnionRsp
	(*SDiffReq)(nil),       // 18: proto.SDiffReq
	(*SDiffRsp)(nil),       // 19: proto.SDiffRsp
	(*SKeyExistsReq)(nil),  // 20: proto.SKeyExistsReq
	(*SKeyExistsRsp)(nil),  // 21: proto.SKeyExistsRsp
	(*SClearReq)(nil),      // 22: proto.SClearReq
	(*SClearRsp)(nil),      // 23: proto.SClearRsp
	(*SExpireReq)(nil),     // 24: proto.SExpireReq
	(*SExpireRsp)(nil),     // 25: proto.SExpireRsp
	(*STTLReq)(nil),        // 26: proto.STTLReq
	(*STTLRsp)(nil),        // 27: proto.STTLRsp
}
var file_cmd_proto_pb_set_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_pb_set_proto_init() }
func file_cmd_proto_pb_set_proto_init() {
	if File_cmd_proto_pb_set_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_pb_set_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAddRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPopRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SIsMemberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SIsMemberRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRandMemberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRandMemberRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMoveRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCardRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMembersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMembersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SUnionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SUnionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SDiffReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SDiffRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKeyExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKeyExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SClearReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SClearRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SExpireReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SExpireRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*STTLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_set_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*STTLRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_pb_set_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_pb_set_proto_goTypes,
		DependencyIndexes: file_cmd_proto_pb_set_proto_depIdxs,
		MessageInfos:      file_cmd_proto_pb_set_proto_msgTypes,
	}.Build()
	File_cmd_proto_pb_set_proto = out.File
	file_cmd_proto_pb_set_proto_rawDesc = nil
	file_cmd_proto_pb_set_proto_goTypes = nil
	file_cmd_proto_pb_set_proto_depIdxs = nil
}
