// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: cmd/proto/pb_zset.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Score  float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Member []byte  `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZAddReq) Reset() {
	*x = ZAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZAddReq) ProtoMessage() {}

func (x *ZAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZAddReq.ProtoReflect.Descriptor instead.
func (*ZAddReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{0}
}

func (x *ZAddReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZAddReq) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ZAddReq) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

type ZAddRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZAddRsp) Reset() {
	*x = ZAddRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZAddRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZAddRsp) ProtoMessage() {}

func (x *ZAddRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZAddRsp.ProtoReflect.Descriptor instead.
func (*ZAddRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{1}
}

func (x *ZAddRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member []byte `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZScoreReq) Reset() {
	*x = ZScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZScoreReq) ProtoMessage() {}

func (x *ZScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZScoreReq.ProtoReflect.Descriptor instead.
func (*ZScoreReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{2}
}

func (x *ZScoreReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZScoreReq) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

type ZScoreRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool    `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Score    float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	ErrorMsg string  `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZScoreRsp) Reset() {
	*x = ZScoreRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZScoreRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZScoreRsp) ProtoMessage() {}

func (x *ZScoreRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZScoreRsp.ProtoReflect.Descriptor instead.
func (*ZScoreRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{3}
}

func (x *ZScoreRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ZScoreRsp) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ZScoreRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ZCardReq) Reset() {
	*x = ZCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCardReq) ProtoMessage() {}

func (x *ZCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCardReq.ProtoReflect.Descriptor instead.
func (*ZCardReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{4}
}

func (x *ZCardReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ZCardRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size     int64  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZCardRsp) Reset() {
	*x = ZCardRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZCardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCardRsp) ProtoMessage() {}

func (x *ZCardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCardRsp.ProtoReflect.Descriptor instead.
func (*ZCardRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{5}
}

func (x *ZCardRsp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ZCardRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member []byte `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZRankReq) Reset() {
	*x = ZRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRankReq) ProtoMessage() {}

func (x *ZRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRankReq.ProtoReflect.Descriptor instead.
func (*ZRankReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{6}
}

func (x *ZRankReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRankReq) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

type ZRankRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank     int64  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRankRsp) Reset() {
	*x = ZRankRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRankRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRankRsp) ProtoMessage() {}

func (x *ZRankRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRankRsp.ProtoReflect.Descriptor instead.
func (*ZRankRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{7}
}

func (x *ZRankRsp) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ZRankRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRevRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member []byte `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZRevRankReq) Reset() {
	*x = ZRevRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRankReq) ProtoMessage() {}

func (x *ZRevRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRankReq.ProtoReflect.Descriptor instead.
func (*ZRevRankReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{8}
}

func (x *ZRevRankReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRevRankReq) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

type ZRevRankRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank     int64  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRevRankRsp) Reset() {
	*x = ZRevRankRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRankRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRankRsp) ProtoMessage() {}

func (x *ZRevRankRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRankRsp.ProtoReflect.Descriptor instead.
func (*ZRevRankRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{9}
}

func (x *ZRevRankRsp) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ZRevRankRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZIncrByReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       []byte  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Increment float64 `protobuf:"fixed64,2,opt,name=increment,proto3" json:"increment,omitempty"`
	Member    []byte  `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZIncrByReq) Reset() {
	*x = ZIncrByReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZIncrByReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZIncrByReq) ProtoMessage() {}

func (x *ZIncrByReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZIncrByReq.ProtoReflect.Descriptor instead.
func (*ZIncrByReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{10}
}

func (x *ZIncrByReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZIncrByReq) GetIncrement() float64 {
	if x != nil {
		return x.Increment
	}
	return 0
}

func (x *ZIncrByReq) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

type ZIncrByRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scores   float64 `protobuf:"fixed64,1,opt,name=scores,proto3" json:"scores,omitempty"`
	ErrorMsg string  `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZIncrByRsp) Reset() {
	*x = ZIncrByRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZIncrByRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZIncrByRsp) ProtoMessage() {}

func (x *ZIncrByRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZIncrByRsp.ProtoReflect.Descriptor instead.
func (*ZIncrByRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{11}
}

func (x *ZIncrByRsp) GetScores() float64 {
	if x != nil {
		return x.Scores
	}
	return 0
}

func (x *ZIncrByRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int64  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *ZRangeReq) Reset() {
	*x = ZRangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRangeReq) ProtoMessage() {}

func (x *ZRangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRangeReq.ProtoReflect.Descriptor instead.
func (*ZRangeReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{12}
}

func (x *ZRangeReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRangeReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ZRangeReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type ZRangeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRangeRsp) Reset() {
	*x = ZRangeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRangeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRangeRsp) ProtoMessage() {}

func (x *ZRangeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRangeRsp.ProtoReflect.Descriptor instead.
func (*ZRangeRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{13}
}

func (x *ZRangeRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ZRangeRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRangeWithScoresReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int64  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *ZRangeWithScoresReq) Reset() {
	*x = ZRangeWithScoresReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRangeWithScoresReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRangeWithScoresReq) ProtoMessage() {}

func (x *ZRangeWithScoresReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRangeWithScoresReq.ProtoReflect.Descriptor instead.
func (*ZRangeWithScoresReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{14}
}

func (x *ZRangeWithScoresReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRangeWithScoresReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ZRangeWithScoresReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type ZRangeWithScoresRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRangeWithScoresRsp) Reset() {
	*x = ZRangeWithScoresRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRangeWithScoresRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRangeWithScoresRsp) ProtoMessage() {}

func (x *ZRangeWithScoresRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRangeWithScoresRsp.ProtoReflect.Descriptor instead.
func (*ZRangeWithScoresRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{15}
}

func (x *ZRangeWithScoresRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ZRangeWithScoresRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRevRangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int64  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *ZRevRangeReq) Reset() {
	*x = ZRevRangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRangeReq) ProtoMessage() {}

func (x *ZRevRangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRangeReq.ProtoReflect.Descriptor instead.
func (*ZRevRangeReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{16}
}

func (x *ZRevRangeReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRevRangeReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ZRevRangeReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type ZRevRangeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRevRangeRsp) Reset() {
	*x = ZRevRangeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRangeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRangeRsp) ProtoMessage() {}

func (x *ZRevRangeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRangeRsp.ProtoReflect.Descriptor instead.
func (*ZRevRangeRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{17}
}

func (x *ZRevRangeRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ZRevRangeRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRevRangeWithScoresReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int64  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *ZRevRangeWithScoresReq) Reset() {
	*x = ZRevRangeWithScoresReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRangeWithScoresReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRangeWithScoresReq) ProtoMessage() {}

func (x *ZRevRangeWithScoresReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRangeWithScoresReq.ProtoReflect.Descriptor instead.
func (*ZRevRangeWithScoresReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{18}
}

func (x *ZRevRangeWithScoresReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRevRangeWithScoresReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ZRevRangeWithScoresReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type ZRevRangeWithScoresRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRevRangeWithScoresRsp) Reset() {
	*x = ZRevRangeWithScoresRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevRangeWithScoresRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevRangeWithScoresRsp) ProtoMessage() {}

func (x *ZRevRangeWithScoresRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevRangeWithScoresRsp.ProtoReflect.Descriptor instead.
func (*ZRevRangeWithScoresRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{19}
}

func (x *ZRevRangeWithScoresRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ZRevRangeWithScoresRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member []byte `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *ZRemReq) Reset() {
	*x = ZRemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRemReq) ProtoMessage() {}

func (x *ZRemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRemReq.ProtoReflect.Descriptor instead.
func (*ZRemReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{20}
}

func (x *ZRemReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRemReq) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

type ZRemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRemRsp) Reset() {
	*x = ZRemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRemRsp) ProtoMessage() {}

func (x *ZRemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRemRsp.ProtoReflect.Descriptor instead.
func (*ZRemRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{21}
}

func (x *ZRemRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ZRemRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZGetByRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Rank int64  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *ZGetByRankReq) Reset() {
	*x = ZGetByRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZGetByRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZGetByRankReq) ProtoMessage() {}

func (x *ZGetByRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZGetByRankReq.ProtoReflect.Descriptor instead.
func (*ZGetByRankReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{22}
}

func (x *ZGetByRankReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZGetByRankReq) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type ZGetByRankRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZGetByRankRsp) Reset() {
	*x = ZGetByRankRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZGetByRankRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZGetByRankRsp) ProtoMessage() {}

func (x *ZGetByRankRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZGetByRankRsp.ProtoReflect.Descriptor instead.
func (*ZGetByRankRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{23}
}

func (x *ZGetByRankRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ZGetByRankRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRevGetByRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Rank int64  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *ZRevGetByRankReq) Reset() {
	*x = ZRevGetByRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevGetByRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevGetByRankReq) ProtoMessage() {}

func (x *ZRevGetByRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevGetByRankReq.ProtoReflect.Descriptor instead.
func (*ZRevGetByRankReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{24}
}

func (x *ZRevGetByRankReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRevGetByRankReq) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type ZRevGetByRankRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRevGetByRankRsp) Reset() {
	*x = ZRevGetByRankRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevGetByRankRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevGetByRankRsp) ProtoMessage() {}

func (x *ZRevGetByRankRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevGetByRankRsp.ProtoReflect.Descriptor instead.
func (*ZRevGetByRankRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{25}
}

func (x *ZRevGetByRankRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ZRevGetByRankRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZScoreRangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Min float64 `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max float64 `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *ZScoreRangeReq) Reset() {
	*x = ZScoreRangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZScoreRangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZScoreRangeReq) ProtoMessage() {}

func (x *ZScoreRangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZScoreRangeReq.ProtoReflect.Descriptor instead.
func (*ZScoreRangeReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{26}
}

func (x *ZScoreRangeReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZScoreRangeReq) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ZScoreRangeReq) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ZScoreRangeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZScoreRangeRsp) Reset() {
	*x = ZScoreRangeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZScoreRangeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZScoreRangeRsp) ProtoMessage() {}

func (x *ZScoreRangeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZScoreRangeRsp.ProtoReflect.Descriptor instead.
func (*ZScoreRangeRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{27}
}

func (x *ZScoreRangeRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ZScoreRangeRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZRevScoreRangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Max float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Min float64 `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
}

func (x *ZRevScoreRangeReq) Reset() {
	*x = ZRevScoreRangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevScoreRangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevScoreRangeReq) ProtoMessage() {}

func (x *ZRevScoreRangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevScoreRangeReq.ProtoReflect.Descriptor instead.
func (*ZRevScoreRangeReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{28}
}

func (x *ZRevScoreRangeReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRevScoreRangeReq) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ZRevScoreRangeReq) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

type ZRevScoreRangeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ErrorMsg string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZRevScoreRangeRsp) Reset() {
	*x = ZRevScoreRangeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRevScoreRangeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRevScoreRangeRsp) ProtoMessage() {}

func (x *ZRevScoreRangeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRevScoreRangeRsp.ProtoReflect.Descriptor instead.
func (*ZRevScoreRangeRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{29}
}

func (x *ZRevScoreRangeRsp) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ZRevScoreRangeRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZKeyExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ZKeyExistsReq) Reset() {
	*x = ZKeyExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZKeyExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKeyExistsReq) ProtoMessage() {}

func (x *ZKeyExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKeyExistsReq.ProtoReflect.Descriptor instead.
func (*ZKeyExistsReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{30}
}

func (x *ZKeyExistsReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ZKeyExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZKeyExistsRsp) Reset() {
	*x = ZKeyExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZKeyExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKeyExistsRsp) ProtoMessage() {}

func (x *ZKeyExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKeyExistsRsp.ProtoReflect.Descriptor instead.
func (*ZKeyExistsRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{31}
}

func (x *ZKeyExistsRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ZKeyExistsRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZClearReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ZClearReq) Reset() {
	*x = ZClearReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZClearReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZClearReq) ProtoMessage() {}

func (x *ZClearReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZClearReq.ProtoReflect.Descriptor instead.
func (*ZClearReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{32}
}

func (x *ZClearReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ZClearRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZClearRsp) Reset() {
	*x = ZClearRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZClearRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZClearRsp) ProtoMessage() {}

func (x *ZClearRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZClearRsp.ProtoReflect.Descriptor instead.
func (*ZClearRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{33}
}

func (x *ZClearRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ZClearRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZExpireReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Duration int64  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *ZExpireReq) Reset() {
	*x = ZExpireReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZExpireReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZExpireReq) ProtoMessage() {}

func (x *ZExpireReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZExpireReq.ProtoReflect.Descriptor instead.
func (*ZExpireReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{34}
}

func (x *ZExpireReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZExpireReq) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type ZExpireRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZExpireRsp) Reset() {
	*x = ZExpireRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZExpireRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZExpireRsp) ProtoMessage() {}

func (x *ZExpireRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZExpireRsp.ProtoReflect.Descriptor instead.
func (*ZExpireRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{35}
}

func (x *ZExpireRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ZTTLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ZTTLReq) Reset() {
	*x = ZTTLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZTTLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZTTLReq) ProtoMessage() {}

func (x *ZTTLReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZTTLReq.ProtoReflect.Descriptor instead.
func (*ZTTLReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{36}
}

func (x *ZTTLReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ZTTLRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl      int64  `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ZTTLRsp) Reset() {
	*x = ZTTLRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_pb_zset_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZTTLRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZTTLRsp) ProtoMessage() {}

func (x *ZTTLRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_pb_zset_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZTTLRsp.ProtoReflect.Descriptor instead.
func (*ZTTLRsp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_pb_zset_proto_rawDescGZIP(), []int{37}
}

func (x *ZTTLRsp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *ZTTLRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_cmd_proto_pb_zset_proto protoreflect.FileDescriptor

var file_cmd_proto_pb_zset_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x7a,
	0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x49, 0x0a, 0x07, 0x5a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x07, 0x5a,
	0x41, 0x64, 0x64, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x35, 0x0a, 0x09, 0x5a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x09, 0x5a, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1c, 0x0a, 0x08, 0x5a, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3a, 0x0a, 0x08, 0x5a, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x34, 0x0a, 0x08, 0x5a, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x08, 0x5a, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x37, 0x0a, 0x0b, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3d, 0x0a,
	0x0b, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x54, 0x0a, 0x0a,
	0x5a, 0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x40, 0x0a, 0x0a, 0x5a, 0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x52, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x09, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x3f, 0x0a, 0x09, 0x5a,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x4f, 0x0a, 0x13,
	0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x49, 0x0a,
	0x13, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x48, 0x0a, 0x0c, 0x5a, 0x52, 0x65, 0x76,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x22, 0x42, 0x0a, 0x0c, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x52, 0x0a, 0x16, 0x5a, 0x52, 0x65, 0x76, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x4c, 0x0a, 0x16, 0x5a, 0x52,
	0x65, 0x76, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x33, 0x0a, 0x07, 0x5a, 0x52, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x35, 0x0a,
	0x07, 0x5a, 0x52, 0x65, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x35, 0x0a, 0x0d, 0x5a, 0x47, 0x65, 0x74, 0x42, 0x79, 0x52, 0x61,
	0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x43, 0x0a, 0x0d, 0x5a,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x38, 0x0a, 0x10, 0x5a, 0x52, 0x65, 0x76, 0x47, 0x65, 0x74, 0x42, 0x79, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x46, 0x0a, 0x10, 0x5a, 0x52,
	0x65, 0x76, 0x47, 0x65, 0x74, 0x42, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x46, 0x0a, 0x0e, 0x5a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x44, 0x0a, 0x0e, 0x5a, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x49, 0x0a, 0x11, 0x5a, 0x52, 0x65, 0x76, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x22, 0x47, 0x0a, 0x11, 0x5a,
	0x52, 0x65, 0x76, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x21, 0x0a, 0x0d, 0x5a, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3b, 0x0a, 0x0d, 0x5a, 0x4b, 0x65, 0x79, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x1d, 0x0a, 0x09, 0x5a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x09, 0x5a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x3a, 0x0a, 0x0a,
	0x5a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x0a, 0x5a, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x1b, 0x0a, 0x07, 0x5a, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x37, 0x0a, 0x07, 0x5a, 0x54, 0x54, 0x4c, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6d, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_pb_zset_proto_rawDescOnce sync.Once
	file_cmd_proto_pb_zset_proto_rawDescData = file_cmd_proto_pb_zset_proto_rawDesc
)

func file_cmd_proto_pb_zset_proto_rawDescGZIP() []byte {
	file_cmd_proto_pb_zset_proto_rawDescOnce.Do(func() {
		file_cmd_proto_pb_zset_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_pb_zset_proto_rawDescData)
	})
	return file_cmd_proto_pb_zset_proto_rawDescData
}

var file_cmd_proto_pb_zset_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_cmd_proto_pb_zset_proto_goTypes = []interface{}{
	(*ZAddReq)(nil),                // 0: proto.ZAddReq
	(*ZAddRsp)(nil),                // 1: proto.ZAddRsp
	(*ZScoreReq)(nil),              // 2: proto.ZScoreReq
	(*ZScoreRsp)(nil),              // 3: proto.ZScoreRsp
	(*ZCardReq)(nil),               // 4: proto.ZCardReq
	(*ZCardRsp)(nil),               // 5: proto.ZCardRsp
	(*ZRankReq)(nil),               // 6: proto.ZRankReq
	(*ZRankRsp)(nil),               // 7: proto.ZRankRsp
	(*ZRevRankReq)(nil),            // 8: proto.ZRevRankReq
	(*ZRevRankRsp)(nil),            // 9: proto.ZRevRankRsp
	(*ZIncrByReq)(nil),             // 10: proto.ZIncrByReq
	(*ZIncrByRsp)(nil),             // 11: proto.ZIncrByRsp
	(*ZRangeReq)(nil),              // 12: proto.ZRangeReq
	(*ZRangeRsp)(nil),              // 13: proto.ZRangeRsp
	(*ZRangeWithScoresReq)(nil),    // 14: proto.ZRangeWithScoresReq
	(*ZRangeWithScoresRsp)(nil),    // 15: proto.ZRangeWithScoresRsp
	(*ZRevRangeReq)(nil),           // 16: proto.ZRevRangeReq
	(*ZRevRangeRsp)(nil),           // 17: proto.ZRevRangeRsp
	(*ZRevRangeWithScoresReq)(nil), // 18: proto.ZRevRangeWithScoresReq
	(*ZRevRangeWithScoresRsp)(nil), // 19: proto.ZRevRangeWithScoresRsp
	(*ZRemReq)(nil),                // 20: proto.ZRemReq
	(*ZRemRsp)(nil),                // 21: proto.ZRemRsp
	(*ZGetByRankReq)(nil),          // 22: proto.ZGetByRankReq
	(*ZGetByRankRsp)(nil),          // 23: proto.ZGetByRankRsp
	(*ZRevGetByRankReq)(nil),       // 24: proto.ZRevGetByRankReq
	(*ZRevGetByRankRsp)(nil),       // 25: proto.ZRevGetByRankRsp
	(*ZScoreRangeReq)(nil),         // 26: proto.ZScoreRangeReq
	(*ZScoreRangeRsp)(nil),         // 27: proto.ZScoreRangeRsp
	(*ZRevScoreRangeReq)(nil),      // 28: proto.ZRevScoreRangeReq
	(*ZRevScoreRangeRsp)(nil),      // 29: proto.ZRevScoreRangeRsp
	(*ZKeyExistsReq)(nil),          // 30: proto.ZKeyExistsReq
	(*ZKeyExistsRsp)(nil),          // 31: proto.ZKeyExistsRsp
	(*ZClearReq)(nil),              // 32: proto.ZClearReq
	(*ZClearRsp)(nil),              // 33: proto.ZClearRsp
	(*ZExpireReq)(nil),             // 34: proto.ZExpireReq
	(*ZExpireRsp)(nil),             // 35: proto.ZExpireRsp
	(*ZTTLReq)(nil),                // 36: proto.ZTTLReq
	(*ZTTLRsp)(nil),                // 37: proto.ZTTLRsp
}
var file_cmd_proto_pb_zset_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_pb_zset_proto_init() }
func file_cmd_proto_pb_zset_proto_init() {
	if File_cmd_proto_pb_zset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_pb_zset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZAddRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZScoreRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZCardRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRankRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRankRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZIncrByReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZIncrByRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRangeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRangeWithScoresReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRangeWithScoresRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRangeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRangeWithScoresReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevRangeWithScoresRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZGetByRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZGetByRankRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevGetByRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevGetByRankRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZScoreRangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZScoreRangeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevScoreRangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRevScoreRangeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZKeyExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZKeyExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZClearReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZClearRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZExpireReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZExpireRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZTTLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_pb_zset_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZTTLRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_pb_zset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_pb_zset_proto_goTypes,
		DependencyIndexes: file_cmd_proto_pb_zset_proto_depIdxs,
		MessageInfos:      file_cmd_proto_pb_zset_proto_msgTypes,
	}.Build()
	File_cmd_proto_pb_zset_proto = out.File
	file_cmd_proto_pb_zset_proto_rawDesc = nil
	file_cmd_proto_pb_zset_proto_goTypes = nil
	file_cmd_proto_pb_zset_proto_depIdxs = nil
}
